find_package(Qt6 REQUIRED COMPONENTS Test)

option(VAST_TEST_VERBOSE "Pass -v2 to the Qt Test binaries" OFF)
if(VAST_TEST_VERBOSE)
    set(VAST_TEST_ARGS -v2)
else()
    set(VAST_TEST_ARGS "")
endif()

add_subdirectory(Audio)
add_subdirectory(Brightness)
add_subdirectory(Clipboard)
add_subdirectory(ImageCache)
add_subdirectory(Jobs)
add_subdirectory(Keylock)
add_subdirectory(Lyrics)
add_subdirectory(MaterialColor)
add_subdirectory(Search)
add_subdirectory(Translation)
add_subdirectory(Utils)
