name: Cachix, binary cache

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  cachix-push:
    name: Build and Push to Cachix
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v14

    - name: Set up Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@v8

    - name: Setup Magic Nix Cache
      uses: cachix/cachix-action@v16
      with:
        name: myamusashi
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build steps
      run: |
        nix build . --log-format bar-with-logs
